services:
  Mink67\MultiPartDeserialize\Controller\EmtityCpntroller:
    tags: [controller.service_arguments]
    class: Mink67\MultiPartDeserialize\Controller\EmtityCpntroller
    autowire: true

  Mink67\MultiPartDeserialize\EventListener\DeserializeListener:
    tags: 
      - {name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest', priority: 2}
    autoconfigure: false
    decorates: 'api_platform.listener.request.deserialize'
    autowire: true

  Mink67\MultiPartDeserialize\Services\FileUploader:
    class: Mink67\MultiPartDeserialize\Services\FileUploader
    autowire: true

  Mink67\MultiPartDeserialize\Annotations\Readers\ReaderFile:
    class: Mink67\MultiPartDeserialize\Annotations\Readers\ReaderFile
    autowire: true      # Automatically injects dependencies in your services.

  
  'Mink67\MultiPartDeserialize\Serializer\MultiPartNormalizer':
        class: 'Mink67\MultiPartDeserialize\Serializer\MultiPartNormalizer'
        # By default .inner is passed as argument
        decorates: 'api_platform.jsonld.normalizer.item'
        autowire: true      # Automatically injects dependencies in your services.
        
  'app.serializer.normalizer.item.json':
        class: 'Mink67\MultiPartDeserialize\Serializer\MultiPartNormalizer'
        decorates: 'api_platform.serializer.normalizer.item'
        autowire: true      # Automatically injects dependencies in your services.

  